name: Publish Retype powered website to GitHub Pages
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  publish:
    name: Publish to retype branch
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: retypeapp/action-build@v1
          
      - uses: retypeapp/action-github-pages@v1
        with:
          update-branch: true


name: Replace CSS Property
on:
  workflow_dispatch:
  push:
    branches:
      - retype

jobs:
  publish:
    name: CSS Property
    runs-on: ubuntu-latest
    steps:
      - uses: jacobtomlinson/gha-find-replace@v2
        with:
          find: ";max-width:1400px"
          replace: ";max-width:2000px" 